### ISSUE TITLE
missing 'ratios' ops in proposal layer 

### ISSUE THREAD

**Issue by terrychenism** [precedenceguo/mx-rcnn#11]
Hi, Jian Guo, Thanks for your great work! I have try your code and some problem in rpn_test stage. I check the code and find 'ratios'  op is missing in proposal layer.  delete “ratios=(0.5, 1, 2) ” in symbol.py  line 216 is okay.

**Comment by terrychenism** [comment]
delete “ratios=(0.5, 1, 2) ” in symbol.py  line 216

**Comment by terrychenism** [comment]
One more question, in train_rnn stage, the input data shape mismatch, maybe you didn't assign the label info. Also plz check line 112 in train_alternate.py, exchange end_epoch and kv_store.

**Comment by precedenceguo** [comment]
Thank you for reporting this!

**Comment by terrychenism** [comment]
Last rcnn training stage problem:


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/mx-rcnn/tools/train_alternate.py", line 209, in <module>
    args.kv_store, args.work_load_list)
  File "/home/mx-rcnn/tools/train_alternate.py", line 168, in alternate_train
    'model/rcnn2', ctx, begin_epoch, rcnn_epoch, frequent, kv_store, work_load_list)
  File "/home/mx-rcnn/tools/train_alternate.py", line 115, in train_rcnn
    solver.fit(train_data, frequent=frequent)
  File "rcnn/solver.py", line 105, in fit
    max_label_shape=max_label_shape)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 288, in _train_multi_device
    executor_manager.copy_to(arg_params, aux_params)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 400, in copy_to
    weight.astype(arg_params[name].dtype).copyto(arg_params[name])
KeyError: 'fc6_weight'


How did you save the unlearnable param(fc6 and fc7) in RPN stage2 ?

**Comment by terrychenism** [comment]
Thanks, everything is okay.

**Comment by precedenceguo** [comment]
mAP should be around 69 with random variation, comparable to py-faster-rcnn.

**Comment by precedenceguo** [comment]
Do we have updates on this issue?

**Comment by terrychenism** [comment]
The result looks very good, but the mAP just is 0.1x.  Could you help me check the evaluation code?

**Comment by precedenceguo** [comment]
The evaluation should have been fine. We have new module api for training now. Please try out latest version though I don't remember any modification to evaluation or testing.
