### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by SJTUzhanglj** [precedenceguo/mx-rcnn#12]
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 314, in 'calling callback function'
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\operator.py", line 600, in creator
    op_prop = prop_cls(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'ratios'
Traceback (most recent call last):
  File "D:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\mx-rcnn\tools\train_alternate.py", line 209, in <module>
    args.kv_store, args.work_load_list)
  File "F:\mx-rcnn\tools\train_alternate.py", line 143, in alternate_train
    test_rpn(image_set, year, root_path, devkit_path, 'model/rpn1', rpn_epoch, ctx)
  File "F:\mx-rcnn\tools\train_alternate.py", line 68, in test_rpn
    sym = get_vgg_rpn_test()
  File "rcnn\symbol.py", line 216, in get_vgg_rpn_test
    op_type='proposal', feat_stride=16, scales=(8, 16, 32), ratios=(0.5, 1, 2), output_score=True)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
WindowsError: exception: access violation writing 0x0000000100000000

Is it because the memory of my PC is insufficient?

**Comment by SJTUzhanglj** [comment]
I think rpn are trained well, the rpn-x.params are already stored

voc_2007_trainval gt roidb loaded from F:\mx-rcnn\data\cache\voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
providing maximum shape [('data', (1, 3, 1000, 1000))] [('label', (1L, 35721L)), ('bbox_target', (1L, 36L, 63L, 63L)), ('bbox_inside_weight', (1L, 36L, 63L, 63L)), ('bbox_outside_weight', (1L, 36L,
 63L, 63L))]

after the above step, maybe the rcnn training step begins that trigger something wrong?
