### ISSUE TITLE
KeyError: fc6_weight

### ISSUE THREAD

**Issue by SJTUzhanglj** [precedenceguo/mx-rcnn#13]
Traceback (most recent call last):
  File "D:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\mx-rcnn\tools\train_alternate.py", line 209, in <module>
    args.kv_store, args.work_load_list)
  File "F:\mx-rcnn\tools\train_alternate.py", line 168, in alternate_train
    'model/rcnn2', ctx, begin_epoch, rcnn_epoch, frequent, kv_store, work_load_list)
  File "F:\mx-rcnn\tools\train_alternate.py", line 115, in train_rcnn
    solver.fit(train_data, frequent=frequent)
  File "rcnn\solver.py", line 105, in fit
    max_label_shape=max_label_shape)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\model.py", line 288, in _train_multi_device
    executor_manager.copy_to(arg_params, aux_params)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\executor_manager.py", line 400, in copy_to
    weight.astype(arg_params[name].dtype).copyto(arg_params[name])
KeyError: 'fc6_weight'

The training process ended when '########## TRAIN RCNN WITH RPN INIT AND DETECTION'
after epoch[0] at this stage.

**Comment by precedenceguo** [comment]
Use `combine_model('model/rpn2', rpn_epoch, 'model/rcnn1', rcnn_epoch, 'model/rcnn2', 0)` as in `tools/train_alternate.py` before rcnn2 training.

**Comment by SJTUzhanglj** [comment]
Thank you! I have completed the training set. But i want to know hown to test my .jpg files with test_final.py

**Comment by SJTUzhanglj** [comment]
I check the code and find a step loading .mat file. The .mat is the result of object proposals that i have to work out by myself?
