### ISSUE TITLE
Error of mxnet/example/rcnn/demo.py

### ISSUE THREAD

**Issue by Keiku** [precedenceguo/mx-rcnn#6]
I executed demo.py(not mx-rcnn but mxnet/example/rcnn), and then I got the below error. What should I do to solve this error? I would like you to write more information about the rcnn because it was difficult for me to understand.

```
Keiku@ubuntu:~/opt/mxnet/example/rcnn$ python demo.py --gpu 0 --prefix ../../tools/caffe_converter/vgg16 --epoch 1
Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    demo_net(detector, os.path.join(os.getcwd(), 'data', 'demo', '000004'))
  File "/home/Keiku/opt/mxnet/example/rcnn/tools/demo_net.py", line 33, in demo_net
    scores, boxes = detector.im_detect(im_array, roi_array)
  File "/home/Keiku/opt/mxnet/example/rcnn/rcnn/detector.py", line 46, in im_detect
    grad_req='null', aux_states=self.aux_params)
  File "/home/Keiku/.pyenv/versions/anaconda-4.0.0/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 783, in bind
    args_handle, args = self._get_ndarray_inputs('args', args, listed_arguments, False)
  File "/home/Keiku/.pyenv/versions/anaconda-4.0.0/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 625, in _get_ndarray_inputs
    raise ValueError('Must specify all the arguments in %s' % arg_key)
ValueError: Must specify all the arguments in args
[11:10:50] /home/Keiku/opt/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:10:50] /home/Keiku/opt/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
[11:10:50] /home/Keiku/opt/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:10:50] /home/Keiku/opt/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
terminate called recursively
terminate called after throwing an instance of 'dmlc::Error'
  what():  [11:10:50] /home/Keiku/opt/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
Aborted (core dumped)
Keiku@ubuntu:~/opt/mxnet/example/rcnn$
```

I put the data/demo as below.

```
Keiku@ubuntu:~/opt/mxnet/example/rcnn/data$ ll
total 468544
drwxrwxr-x 5 Keiku Keiku      4096 May 25 11:35 ./
drwxrwxr-x 8 Keiku Keiku      4096 May 27 11:00 ../
drwxrwxr-x 2 Keiku Keiku      4096 May 25 10:51 demo/
drwxr-xr-x 2 Keiku Keiku      4096 Apr 30  2015 selective_search_data/
-rw-rw-r-- 1 Keiku Keiku 479764750 Apr 30  2015 selective_search_data.tgz
drwxrwxr-x 2 Keiku Keiku      4096 May 25 10:32 VOCdevkit/

Keiku@ubuntu:~/opt/mxnet/example/rcnn/data/demo$ ll
total 224
drwxrwxr-x 2 Keiku Keiku   4096 May 25 10:51 ./
drwxrwxr-x 5 Keiku Keiku   4096 May 25 11:35 ../
-rw-rw-r-- 1 Keiku Keiku  23296 May 25 10:51 000004_boxes.mat
-rw-rw-r-- 1 Keiku Keiku 102770 May 25 10:51 000004.jpg
-rw-rw-r-- 1 Keiku Keiku  16648 May 25 10:51 001551_boxes.mat
-rw-rw-r-- 1 Keiku Keiku  69440 May 25 10:51 001551.jpg
Keiku@ubuntu:~/opt/mxnet/example/rcnn/data/demo$
```

**Comment by precedenceguo** [comment]
I have not been able to reproduce this error. Since MXNet has a new release v0.7, could you please update your mxnet so that we can have the same environment?

**Comment by Keiku** [comment]
Sorry, I just know a new release v0.7 now. I will try rcnn on v0.7, and I will let you know whether it will work well.

**Comment by Keiku** [comment]
I got a same error. "detector.im_detect()" in demo_net.py doesn't work well.

**Comment by precedenceguo** [comment]
I noticed something. You used `--prefix ../../tools/caffe_converter/vgg16` as parameter. This is an ImageNet classification model rather than a detection network model. It cannot be used as the demo model.

**Comment by Keiku** [comment]
I have just understood my mistake. I executed "fetch_fast_rcnn_models.sh" and I downloaded caffemodels, but I don't find prototxt and which should I choose caffemodel? 

```
xke-kuroyanagi@ubuntu:~/opt/mxnet/example/rcnn/fast_rcnn_models$ ll
total 1087224
drwxrwxr-x 2 xke-kuroyanagi xke-kuroyanagi      4096 Apr 29  2015 ./
drwxrwxr-x 8 xke-kuroyanagi xke-kuroyanagi      4096 May 27 18:56 ../
-rw-rw-r-- 1 xke-kuroyanagi xke-kuroyanagi 229195587 Apr 29  2015 caffenet_fast_rcnn_iter_40000.caffemodel
-rw-rw-r-- 1 xke-kuroyanagi xke-kuroyanagi 538766130 Apr 29  2015 vgg16_fast_rcnn_iter_40000.caffemodel
-rw-rw-r-- 1 xke-kuroyanagi xke-kuroyanagi 345334609 Apr 29  2015 vgg_cnn_m_1024_fast_rcnn_iter_40000.caffemodel
xke-kuroyanagi@ubuntu:~/opt/mxnet/example/rcnn/fast_rcnn_models$
```

**Comment by precedenceguo** [comment]
Please refer to https://github.com/rbgirshick/fast-rcnn for more detailed explanation.

**Comment by Keiku** [comment]
Sorry for bother you. I'm going to study now. Thank you for your advice.

**Comment by precedenceguo** [comment]
Close since we don't have this demo anymore.
