### ISSUE TITLE
KeyError: 'fc8_bias' while training

### ISSUE THREAD

**Issue by haria** [precedenceguo/mx-rcnn#7]
Hi @precedenceguo 

I got a error message say KeyError: 'fc8_bias' while trying your example, I check the train.prototxt and I didn't find fc8 layer, so I would like to confirm what's train.prototxt file do you use, can I remove following two line?
```python
     del args['fc8_bias']
     del args['fc8_weight']
```

```shell
haria@haria-All-Series:~/mxnet/example/rcnn$ python train.py 
voc_2007_train gt roidb loaded from /home/haria/mxnet/example/rcnn/data/cache/voc_2007_train_gt_roidb.pkl
voc_2007_train ss roidb loaded from /home/haria/mxnet/example/rcnn/data/cache/voc_2007_train_ss_roidb.pkl
append flipped images to roidb
Premature end of JPEG file
Premature end of JPEG file
Premature end of JPEG file
Premature end of JPEG file
add bounding box regression targets
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    args.prefix, ctx, args.begin_epoch, args.end_epoch, args.frequent)
  File "/home/haria/mxnet/example/rcnn/tools/train_net.py", line 39, in train_net
    del args['fc8_bias']
KeyError: 'fc8_bias'
terminate called recursively
terminate called after throwing an instance of 'dmlc::Error'
  what():  driver shutting down

```

thank you!

**Comment by precedenceguo** [comment]
`mxnet/tools/caffe_converter` refer to the vgg16 by the original authors. It is okay to drop the statements.

**Comment by haria** [comment]
thank you!
