### ISSUE TITLE
training_alternate.py TypeError: _train_multi_device() got an unexpected keyword argument 'max_label_shape'

### ISSUE THREAD

**Issue by qingswu** [precedenceguo/mx-rcnn#9]
I've got an type error while running the training script with default parameters. I've built mxnet using your folk. Tested both in Ubuntu and OS X with or without CUDA.

The running output is:

INFO:root:########## TRAIN RPN WITH IMAGENET INIT
wrote gt roidb to mx-rcnn/data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
providing maximum shape [('data', (1, 3, 1000, 1000))] [('label', (1, 35721)), ('bbox_target', (1, 36, 63, 63)), ('bbox_inside_weight', (1, 36, 63, 63)), ('bbox_outside_weight', (1, 36, 63, 63))]
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "mx-rcnn/tools/train_alternate.py", line 209, in <module>
    args.kv_store, args.work_load_list)
  File "mx-rcnn/tools/train_alternate.py", line 137, in alternate_train
    'model/rpn1', ctx, begin_epoch, rpn_epoch, frequent, kv_store, work_load_list)
  File "/mx-rcnn/tools/train_alternate.py", line 61, in train_rpn
    solver.fit(train_data, frequent=frequent)
  File "rcnn/solver.py", line 105, in fit
    max_label_shape=max_label_shape)
TypeError: _train_multi_device() got an unexpected keyword argument 'max_label_shape'

**Comment by precedenceguo** [comment]
Install a forked MXNet at [MXNet-detection](https://github.com/precedenceguo/mxnet/tree/detection). Follow the instructions at http://mxnet.readthedocs.io/en/latest/how_to/build.html. Install the python interface. We are working to use module API and deprecate this fork asap. However right now please try a special fix at this fork.

**Comment by qingswu** [comment]
checkout detection worked, you'd better add this in the README.md
